export const products = [
  {
    id: 1,
    title: "Waffle",
    descraption: "Waffle with Berries",
    price: 6.5,
    thumb: "../images/waffle.jpg",
  },
  {
    id: 2,
    title: "Crème Brûlée",
    descraption: "Vanilla Bean Crème Brûlée",
    price: 7.0,
    thumb: "../images/crame-brulee.jpg",
  },
  {
    id: 3,
    title: "Macaron",
    descraption: "Macaron Mix of Five",
    price: 8.0,
    thumb: "../images/macaron.jpg",
  },
  {
    id: 4,
    title: "Tiramisu",
    descraption: "Classic Tiramisu",
    price: 5.5,
    thumb: "../images/tramisu.jpg",
  },
  {
    id: 5,
    title: "Baklava",
    descraption: "Pistachio Baklava",
    price: 4.0,
    thumb: "../images/baklava.jpg",
  },
  {
    id: 6,
    title: "Pie",
    descraption: "Lemon Meringue Pie",
    price: 5.0,
    thumb: "../images/pie.jpg",
  },
  {
    id: 7,
    title: "Cake",
    descraption: "Red Velvet Cake",
    price: 4.5,
    thumb: "../images/cake.jpg",
  },
  {
    id: 8,
    title: "Brownie",
    descraption: "Salted Caramel Brownie",
    price: 5.5,
    thumb: "../images/brownie.jpg",
  },
  {
    id: 9,
    title: "Panna Cotta",
    descraption: "Vanilla Panna Cotta",
    price: 6.5,
    thumb: "../images/panna-cotta.jpg",
  },
];
